check if file exist. then move to root dir for upload

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -52,17 +52,20 @@ jobs:
         env:
           ENV: test
 
+      - name: Move .coverage to root
+        run: |
+          if [ -f atomsci/ddm/test/unit/.coverage ]; then
+            mv atomsci/ddm/test/unit/.coverage .
+          fi
+
+      - name: Check for .coverage file
+        run: ls -l .coverage || echo ".coverage not found"
+
       - name: Upload coverage-part1
         uses: actions/upload-artifact@v4
         with:
           name: coverage-part1
           path: .coverage
-      
-      - name: Check current directory
-        run: pwd
-
-      - name: Check for .coverage file
-        run: ls -l .coverage
 
   pytest-integrative-1:
     runs-on: ubuntu-24.04
@@ -97,6 +100,7 @@ jobs:
           pip install -e .
           if [ -f pip/cpu_requirements.txt ]; then pip install -r pip/cpu_requirements.txt; fi
           if [ -f pip/dev_requirements.txt ]; then pip install -r pip/dev_requirements.txt; fi
+     
       - name: pytest
         run: |
           # TODO: Run this test with pytest for paralell testing
@@ -104,17 +108,21 @@ jobs:
           cd atomsci/ddm/test/integrative && ./integrative_batch_chunk_tests 0
         env:
           ENV: test
+
+      - name: Move .coverage to root
+        run: |
+          if [ -f atomsci/ddm/test/integrative/.coverage ]; then
+            mv atomsci/ddm/test/integrative/.coverage .
+          fi
+
+      - name: Check for .coverage file
+        run: ls -l .coverage || echo ".coverage not found"
+
       - name: Upload coverage-part2
         uses: actions/upload-artifact@v4
         with:
           name: coverage-part2
           path: .coverage
-  
-      - name: Check current directory
-        run: pwd
-
-      - name: Check for .coverage file
-        run: ls -l .coverage
 
   pytest-integrative-2:
     runs-on: ubuntu-24.04
@@ -149,25 +157,29 @@ jobs:
           pip install -e .
           if [ -f pip/cpu_requirements.txt ]; then pip install -r pip/cpu_requirements.txt; fi
           if [ -f pip/dev_requirements.txt ]; then pip install -r pip/dev_requirements.txt; fi
+     
       - name: pytest
         run: |
           # TODO: Run this test with pytest for paralell testing
           # python3.9 -m pytest -n 2 --capture=sys --capture=fd --cov=atomsci -vv atomsci/ddm/test/integrative
           cd atomsci/ddm/test/integrative && ./integrative_batch_chunk_tests 1
         env:
-          ENV: test
-      
+          ENV: test 
+     
+      - name: Move .coverage to root
+        run: |
+          if [ -f atomsci/ddm/test/integrative/.coverage ]; then
+            mv atomsci/ddm/test/integrative/.coverage .
+          fi
+
+      - name: Check for .coverage file
+        run: ls -l .coverage || echo ".coverage not found"
+        
       - name: Upload coverage-part3
         uses: actions/upload-artifact@v4
         with:
           name: coverage-part3
           path: .coverage
-
-      - name: Check current directory
-        run: pwd
-
-      - name: Check for .coverage file
-        run: ls -l .coverage
 
   pytest-integrative-3:
     runs-on: ubuntu-24.04
@@ -210,18 +222,21 @@ jobs:
           cd atomsci/ddm/test/integrative && ./integrative_batch_chunk_tests 2
         env:
           ENV: test
-      
+
+      - name: Move .coverage to root
+        run: |
+          if [ -f atomsci/ddm/test/integrative/.coverage ]; then
+            mv atomsci/ddm/test/integrative/.coverage .
+          fi
+
+      - name: Check for .coverage file
+        run: ls -l .coverage || echo ".coverage not found"
+
       - name: Upload coverage-part4
         uses: actions/upload-artifact@v4
         with:
           name: coverage-part4
           path: .coverage
-  
-      - name: Check current directory
-        run: pwd
-        
-      - name: Check for .coverage file
-        run: ls -l .coverage
 
   pytest-integrative-4:
     runs-on: ubuntu-24.04
@@ -264,18 +279,21 @@ jobs:
           cd atomsci/ddm/test/integrative && ./integrative_batch_chunk_tests 3
         env:
           ENV: test
-      
+
+      - name: Move .coverage to root
+        run: |
+          if [ -f atomsci/ddm/test/integrative/.coverage ]; then
+            mv atomsci/ddm/test/integrative/.coverage .
+          fi
+
+      - name: Check for .coverage file
+        run: ls -l .coverage || echo ".coverage not found"
+
       - name: Upload coverage-part5
         uses: actions/upload-artifact@v4
         with:
           name: coverage-part5
           path: .coverage
-  
-      - name: Check current directory
-        run: pwd
-
-      - name: Check for .coverage file
-        run: ls -l .coverage
 
   combine-and-upload:
     name: Combine codecov and upload
